name = "ghr-to-cfr"
main = "./dist/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[build]
command = "npm run build"
watch_dir = "src"

[vars]
ENVIRONMENT = "production"
REPO_1 = "2dust/v2rayN:/z_最好会点小魔法"
REPO_2 = "2dust/v2rayNG:/z_最好会点小魔法"

[[kv_namespaces]]
binding = "SYNC_STATUS"
id = "671e98de4e3c4d44a08cba27826cf7b3"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "github-releases"

[observability.logs]
enabled = true