name = "ghrtocfr"
main = "src/index.js"
compatibility_date = "2025-01-01"

[site]
bucket = "./public"

[build]
command = "npm run build"
watch_dir = "src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[rules]]
type = "Text"
globs = ["**/*.css"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "SYNC_STATUS"
id = "671e98de4e3c4d44a08cba27826cf7b3"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "github-releases"

[observability.logs]
enabled = true