name = "GHRtoCFR"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[build]
command = "npm run build"
watch_dir = "src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[rules]]
type = "CSS"
globs = ["**/*.css"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "SYNC_STATUS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "your-bucket-name"

[observability.logs]
enabled = true