name = "ghrtocfr"
main = "src/index.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 0 * * *"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "github-releases"

[observability.logs]
enabled = true